server:
  port: 8083

spring:
  datasource:
    druid:
      name: druid-database-fireiot
      url: jdbc:postgresql://localhost:5432/test
      username: postgres
      password: 123456
      driver-class-name: org.postgresql.Driver
      filters: stat
      # 初始连接
      initialSize: 1
      # 最大连接数
      maxActive: 20
      # 获取的最长等待时
      maxWait: 60000
      # 最小空闲连接数
      minIdle: 1
      # 每一分钟执行空闲连接回收
      timeBetweenEvictionRunsMillis: 60000
      # 每十分钟回收空闲连接
      minEvictableIdleTimeMillis: 600000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  jpa:
    #open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      #use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false

    #数据库方式
    job-store-type: jdbc
    #初始化表结构
    #jdbc:
    #initialize-schema: never
  quartz:
    jdbc:
      initialize-schema: never
    job-store-type: jdbc
    properties:
      org.quartz.threadPool.threadCount: 5
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.dataSource: druid-database-fireiot

